### ISSUE TITLE
Category blocking isn't working

### ISSUE THREAD

**Issue by MuhammadBayiz** [FarisHijazi/Rarbg-Enhancer-UserScript#10]
It's been awhile since blocking of the category was working, now it isn't working at all

**Comment by FarisHijazi** [comment]
which mirror of the website are you using, could you share the exact URL
some of the mirrors act differently FYI

**Comment by MuhammadBayiz** [comment]
Sorry for delay response I'm using Rarbg.to with Kiwi Browser in Android 12.1 it was working before but after the update of adding Script Setting Button it wasn't working anymore
Edit: Although tried all the mirrors but still not blocking
Edit2: PS the browser version is 101.0.4951.57 based on chromium

**Comment by FarisHijazi** [comment]
This is super cool, i had no idea there was a browser on mobile that allowed tampermonkey and also has a developer console!
Def gonna start using this, lemme test stuff and get back to you

**Comment by MuhammadBayiz** [comment]
Fantastic it's working now but the only issue is the XXX section is still showing in the category list in left side of the page everything else is good and blocking 👌

**Comment by FarisHijazi** [comment]
@MohamadBayz added this feature, now the buttons should get removed

**Comment by MuhammadBayiz** [comment]
New Little Bug:
After Blocking A Category That Category's Section Still Shows In The Top 10 Page.
(See Attached Pictures)
![Screenshot_20221216-094407_Chrome](https://user-images.githubusercontent.com/63660736/208038848-61a15519-a2ae-4c2b-bb23-ea80c35f0681.png)
