### ISSUE TITLE
Doesn't work in Firefox 100.

### ISSUE THREAD

**Issue by windowsxp1010** [FarisHijazi/Rarbg-Enhancer-UserScript#11]
Doesn't work in Firefox 100. I am using Greasemonkey. It gives an error like this:

https://prnt.sc/ybHjODvHTvFv

**Comment by FarisHijazi** [comment]
Ok solution should be simple, i should probably just remove registermenucommand or add a pollyfill
If you use Tampermonkey it should work on all browsers

I'll fix that in a week or 2
