### ISSUE TITLE
22pixx shows thumbnail

### ISSUE THREAD

**Issue by MuhammadBayiz** [FarisHijazi/Rarbg-Enhancer-UserScript#13]
Hi i wanted to report that 22 pixx shows thumbnail instead of a full quality picture when i fetch a torrent thumbnail and open the image it shows a small blurry low quality picture.

**Comment by MuhammadBayiz** [comment]
If it help with rarbg helper userscript i get a nice quality picture

**Comment by FarisHijazi** [comment]
Works fine with me, note that there are different urls for this same site, i need you to send me the link and the thumbnail url if you want me to add this to the code

**Comment by MuhammadBayiz** [comment]
Sorry with the new update i guess it's fixed, before when we had fetch thumbnails button and when it fetched the pictures 22pixx was blurry but now that the button is gone there's no problem

**Comment by FarisHijazi** [comment]
Again, the images are blurry by default, but one of the script's features is that it can map the thumbnail (blurry) url to the original fullres url, but I don't have alllll the mappings

A mapping may look like


Fullres:  https://.......1234/o/4567.png
Thumb: https://.......1234/os/4567.png


I manually had to add them all, so if you find new patterns I'll be happy to add them

**Comment by MuhammadBayiz** [comment]
Great if i find any I'll let you know
