### ISSUE TITLE
Thumbnails are gone in new update

### ISSUE THREAD

**Issue by MuhammadBayiz** [FarisHijazi/Rarbg-Enhancer-UserScript#14]
Hi I use Kiwi Browser in Android 12 and i  just updated the user script and reload RARBG page and noticed that the thumbnails were gone also the fetch thumbnail button
Edit: the Problem appeard in version 1.6.11 but in version 1.6.8 is fine 
![Screenshot_20220525-082334_Kiwi Browser](https://user-images.githubusercontent.com/63660736/170186028-e558f9d6-0054-4c85-992d-07a3d220caec.png)

**Comment by FarisHijazi** [comment]
the thumbnails are there actually but they're super tiny, you have to press those buttons to make the images bigger/smaller

the (-) / (+) buttons next to the `thumbnails` column header, also make sure to update the script, you don't seem to have those buttons

closing this, reopen it if it doesn't work

**Comment by MuhammadBayiz** [comment]
Even though i updated the script to latest version still can't see the button but I can see thumbnails, looks really tiny

**Comment by FarisHijazi** [comment]
Try going to settings and reset defaults.
Another way to modify the size is to press - and = on the keyboard
Also you can modify the imgScale value in the settings

**Comment by MuhammadBayiz** [comment]
You were right after restarting the settings and changing the scale i was able to get back original thumbnail size, thanks
