### ISSUE TITLE
ios safari

### ISSUE THREAD

**Issue by Yumega** [FarisHijazi/Rarbg-Enhancer-UserScript#15]
Thanks for the great script, works so well on PC, but doesn't work on ios safari, using stay2(like Tampermonkey on PC), is it possible to make one for ios  safari only bypass the CAPTCHA

**Comment by FarisHijazi** [comment]
this is a tough request, because I don't have a mac 😅 , not sure how I can test this
Could you show me what types of errors you're getting? go to the [devtools](https://support.apple.com/en-sa/guide/safari/sfri20948/mac) and show me the errors please

**Comment by Yumega** [comment]
> this is a tough request, because I don't have a mac 😅 , not sure how I can test this Could you show me what types of errors you're getting? go to the [devtools](https://support.apple.com/en-sa/guide/safari/sfri20948/mac) and show me the errors please

well,it's okay. how to disable the sound. I can  hear the sould each time I use

**Comment by FarisHijazi** [comment]
>  is it possible to make one for ios  safari only bypass the CAPTCHA

There is already another script only for the capctha, see the readme

**Comment by FarisHijazi** [comment]
I've made some fixes where thumbnails weren't being shown on safari.

As per sound, there's no way to remove the sound, i could add sn option for that later
