### ISSUE TITLE
Userscript doesn't work now

### ISSUE THREAD

**Issue by MuhammadBayiz** [FarisHijazi/Rarbg-Enhancer-UserScript#18]
After the update for 1.6.18 the userscript doesn't work at all on my Android i haven't checked on my laptop, i get this error in the console
![chrome_screenshot_Aug 6, 2022 8_38_46 AM GMT+03_00](https://user-images.githubusercontent.com/63660736/183235835-627e7597-792e-4474-9939-6c089ae20f57.png)

**Comment by Joyhugo02** [comment]
not working

**Comment by FarisHijazi** [comment]
try installing it again, there's an intermediate version which had this bug, I'm closing for now cuz I'm pretty sure it works.
Feel free to reopen it if the issue persists
