### ISSUE TITLE
Torrents disappearing after page load

### ISSUE THREAD

**Issue by MuhammadBayiz** [FarisHijazi/Rarbg-Enhancer-UserScript#19]
Hi! With version 1.6.19 "Reset to defaults" doesn't work  when i press it and some torrent with 1080p disappears from search
![Screenshot_20220817-160634_Kiwi Browser](https://user-images.githubusercontent.com/63660736/185142235-1b145ac7-cd80-41dc-86fb-5480cf5b539e.png)
I've Kiwi Browser version 103.0.5060.104 with android 12.1
Please let me know about any further info about the issue, regards.

**Comment by FarisHijazi** [comment]
there doesn't seem to be an actual error here, these errors are always thrown even when the script works

is it still not working? be sure to upgrade to the latest version

**Comment by MuhammadBayiz** [comment]
Sorry i wasn't specific with the issue and should've reopened the old issue that i opened with kiwi, anyway some of the torrents that has 1080p when i seqrch for them they disappear in the search results after the script runs, like this one "NubileFilms.22.09.26.Anna.Claire.Clouds.And.Lily.Larimar.Best.Laid.Plans" if you search for this first before the script runs you see 4 torrents one with 1080p quality, but after the script runs it becomes 3 torrents and the one with 1080p disappears.
Sorry for the inconvenient torrent but i couldn't find another torrent that has this issue where 1080p disappear it seems that this issue only happens with XXX Category torrents

**Comment by FarisHijazi** [comment]
Ok go to the settings and disable deduplicateTorrents
There was a bug in the code, any old users will need to do this step

**Comment by MuhammadBayiz** [comment]
Fixed! Thanks allot!
