### ISSUE TITLE
could you make a standalone version that only solves captcha?

### ISSUE THREAD

**Issue by ak800i** [FarisHijazi/Rarbg-Enhancer-UserScript#2]
could you make a standalone version that only solves captcha?

**Comment by FarisHijazi** [comment]
Hi, sorry I haven't responded earlier, i think i had notifications off, actually ya we can have a standalone captcha solver.

I'll probably keep it in the same repo

**Comment by FarisHijazi** [comment]
Please find the file [Rarbg-CAPTCHA-solver.user.js](https://github.com/FarisHijazi/Rarbg-Enhancer-UserScript/blob/master/Rarbg-CAPTCHA-solver.user.js)
