### ISSUE TITLE
Weird include in script

### ISSUE THREAD

**Issue by drelephant** [FarisHijazi/Rarbg-Enhancer-UserScript#23]
Can anyone please explain what this include is for in the script?

````
// @include      /https?:\/\/.*u=MTcyLjIxLjAuMXw6Ly9yYXJiZy50by90b3JyZW50LzIyMDg3MjYwfE1vemlsbGEvNS4wIChXaW5kb3dzIE5UIDEwLjA7IFdpbjY0OyB4NjQpIEFwcGxlV2ViS2l0LzUzNy4zNiAoS0hUTUwsIGxpa2UgR2Vja28pIENocm9tZS83OS4wLjM5NDUuMTMwIFNhZmFyaS81MzcuMzZ8ODc4MDQz.*/
````

**Comment by FarisHijazi** [comment]
took it from some other rarbg script, I thought maybe it worked for some torrent mirror and this is just the special url for rarbg
either way it's not a major security risk to have that
