### ISSUE TITLE
[Request] Highlight title for any resolution

### ISSUE THREAD

**Issue by cjrayance** [FarisHijazi/Rarbg-Enhancer-UserScript#25]
Hi, I would like you to add a feature for highlighting the video resolution in the browse page, for example 4K= Green.
1080p = Yello
720p = red
480p purple

like this picture 

![image](https://github.com/FarisHijazi/Rarbg-Enhancer-UserScript/assets/122617363/7f8353a6-62b5-477c-8cf3-3c8a5fd9a1d1)

**Comment by FarisHijazi** [comment]
Could you share the code for this so i can integrate it
