### ISSUE TITLE
rarbgto.org close

### ISSUE THREAD

**Issue by Alexisback** [FarisHijazi/Rarbg-Enhancer-UserScript#27]
Hello guys,
We would like to inform you that we have decided to shut down our site.
The past 2 years have been very difficult for us - some of the people in our team died due to covid complications,
others still suffer the side effects of it - not being able to work at all.
Some are also fighting the war in Europe - ON BOTH SIDES.
Also, the power price increase in data centers in Europe hit us pretty hard.
Inflation makes our daily expenses impossible to bare.
Therefore we can no longer run this site without massive expenses that we can no longer cover out of pocket.
After an unanimous vote we've decided that we can no longer do it.
We are sorry :(
Bye

https://rarbgto.org/torrents.php

**Comment by FarisHijazi** [comment]
yes this is very unfortunate

but there are very similar mirrors like: https://rargb.to
