### ISSUE TITLE
Magnet image URL doesnt load

### ISSUE THREAD

**Issue by tyhallcsu** [FarisHijazi/Rarbg-Enhancer-UserScript#29]
I changed the magnet URL because it wasn't loading for me. 
This one does: https://rarbg.torrentbay.net/static/img/magnet.gif

`const MAGNET_ICO = "https://rarbg.torrentbay.net/static/img/magnet.gif";
`

**Comment by tyhallcsu** [comment]
https://dyncdn.me/static/20/img/magnet.gif was the url that didnt work. Maybe just encode the image into the script instead of loading it via CDN ?

**Comment by FarisHijazi** [comment]
thanks for letting me know
I fixed it in 0f990e5
please test it out and lemme know
