### ISSUE TITLE
Not working in Firefox 

### ISSUE THREAD

**Issue by mat926** [FarisHijazi/Rarbg-Enhancer-UserScript#4]
I just installed this script and I don't see any of the enhancements . FF version is 91.0.2, GM 4.11 , script version 1.5.1

**Comment by FarisHijazi** [comment]
I'll look into that
Thanks for the issue

Please mention any errors you get in the console, press F12 and navigate to the console section, and run a rarbg page, please post the console here

**Comment by FarisHijazi** [comment]
just checked it, working on `FF 91.0.2 (64-bit)`
make sure you don't have more than one script running
