### ISSUE TITLE
[Bug] Large fonts 

### ISSUE THREAD

**Issue by mat926** [FarisHijazi/Rarbg-Enhancer-UserScript#5]
Using the Brave browser w/ Tampermonkey. On the search page the font & image appears too big.

![image](https://user-images.githubusercontent.com/46114199/132380730-e94e515d-1941-45f8-a6b0-1487439f075a.png)

**Comment by Alexisback** [comment]
I also have this problem,
Firefox 78.14.0Esr (64 bit) 

![sshot-1](https://user-images.githubusercontent.com/18039740/132383899-255ced15-2ea7-4ed1-b1fd-b0ec82ec60c6.png)

**Comment by FarisHijazi** [comment]
Actually, from what I recall, this was intentional, I made the fonts bigger

One thing you can do to switch the thumbnails to fullres is to press the ` key to toggle

Another thing is to press `-` and `=` to make the images bigger or smaller

I can remove this font feature

Thanks for your feedback

**Comment by mat926** [comment]
> Actually, from what I recall, this was intentional, I made the fonts bigger
> 
> One thing you can do to switch the thumbnails to fullres is to press the ` key to toggle
> 
> Another thing is to press `-` and `=` to make the images bigger or smaller
> 
> I can remove this font feature
> 
> Thanks for your feedback

You could add an option for it in settings, for the font and image sizes. Ideally i would like everything to be consistent to what RARGB already has.

**Comment by FarisHijazi** [comment]
turns out this was due to the automatic coloring of seeders, it also makes fonts bigger when seeds are more, I'll disable that

**Comment by mat926** [comment]
I tried your latest update and there has been no change 

![image](https://user-images.githubusercontent.com/46114199/136494117-058b5dc6-e975-4df7-93eb-951366723804.png)

**Comment by FarisHijazi** [comment]
the font size is the same as the original rarbg, it did change

if you want to turn of the colors, set `seedEffects: false` in settings

**Comment by mat926** [comment]
I changed some settings but still do not notice any changes.
![image](https://user-images.githubusercontent.com/46114199/136727472-7b39d1e2-fe7d-4c57-a83d-4099bf725dfd.png)

**Comment by FarisHijazi** [comment]
in the settings actually, go to the storage tab of the script, not the code itself

but int this image you don't seem to have the storage tab, it's supposed to be right next to the Settings tab. when editing, you need to actually close all rarbg windows first.

**Comment by mat926** [comment]
I closed all the tabs but I am still not seeing storage tab.

**Comment by FarisHijazi** [comment]
I'm sure that if you disable seedEffects that this issue will be resolved, but the fact that you can't disable it is another issue on it's own, it's a tampermonkey issue (or a fix in the tampermonkey settings)

also if you notice, the large fonts did go away, but disabling seedEffects will disable the background coloring of torrents (red for few seeds and green for lots of seeds)

try uninstalling and reinstalling the script and make sure there aren't 2 scripts somehow

**Comment by FarisHijazi** [comment]
@leodoi3 feel free to re-open the issue if it's not resolved
I'll be closing it now

**Comment by mat926** [comment]
I was able to get the storage tab to show up (change config mode to Advance in TM).
I disabled the seedeffects but I'm not sure if that made any difference, layout-wise, I dont see the background colors though. 

![image](https://user-images.githubusercontent.com/46114199/137646335-e389f14a-de08-42b0-88ee-ec34d799fe48.png)

**Comment by FarisHijazi** [comment]
the font size is now default and it removed the large font

you want google search and thumbnails to be removed too?
what's your main use-case for the script?

**Comment by mat926** [comment]
Yes you're right , it's all good now you can close the issue,
