### ISSUE TITLE
Feature request: More options

### ISSUE THREAD

**Issue by mat926** [FarisHijazi/Rarbg-Enhancer-UserScript#6]
The script is nice but it's missing a few features i would like added: 

* Ability to customize the row height. 
    * For the thumbnail column , you could still resize the images smaller , but only show the enlarged image when you hover the mouse (see my other suggestion) 

* Change the popup scale of an image when you hover over a thumbnail. 

* Add back the Recommended Torrents section near the top.

**Comment by FarisHijazi** [comment]
hmmm

these seem simple and implementation should be simple, but I'd like a clean way to organize the options and display them to the user

there are 3 ways I can think of to have options for users:

1. add an object/dictionary/map at the top of the code that the user can change.
     - The problem with this is that a new script update will delete the old settings (as the code is updated)
2. user is expected to change the storage tab from tampermonkey, which requires advanced mode to be on.
    - This is a bit more annoying to code
3. making a UI for the user.
    - This is probably the most user friendly way, but takes work, and something out there probably exists, I'm not good at UI, but if you find me something or code it I'll be happy to add it to this project and my other projects


it would be helpful if you could give me an idea of what type of UI the user should be dealing with, or if you know another script that has such options, please do share it and I'll look at the code

**Comment by mat926** [comment]
I personally think the easiest would be #3 since it is user friendly, the other options seem it's annoying.  Sorry  I dont have any idea for a UI yet.

**Comment by FarisHijazi** [comment]
https://stackoverflow.com/a/43462416/7771202
this answer seems to be helpful, will look into this stuff later

**Comment by FarisHijazi** [comment]
resolved in ca6f15f76a17e8cee8e3971c1544b74b7b40f552
