### ISSUE TITLE
Request: Screenshots for torrents

### ISSUE THREAD

**Issue by mat926** [FarisHijazi/Rarbg-Enhancer-UserScript#8]
On porn torrents could you add an extra column for screenshots please? When it’s clicked have it open the full size image in a new tab.

**Comment by FarisHijazi** [comment]
The script runs the same fo all categories, movies, music, etc.

It does modify the page if it has screenshots

Isn't there already a column for screenshots? The script is a bit finicky so try to zoom in and out for the screenshots to appear.

If that's not what you meant, could you clarify which screenshots you mean

**Comment by mat926** [comment]
The screenshot I meant was the one showing multiple frames.  On the torrent page it's sometimes found under "Description". You could add a second screenshot column that shows that.

**Comment by FarisHijazi** [comment]
ok now that I'm looking into it, do you mean fetching the contents from the torrent page itself and putting it in the search page next to each torrent? that would cause way too many requests and your IP would get banned, I already tried something like that before

closing this issue as there is no good solution for it
besides there's a new feature "fetchExtraThumbnails"

closing this issue, reopen it if I misunderstood
