### ISSUE TITLE
Not working on chrome Error at GM_Fetch2

### ISSUE THREAD

**Issue by Michedelic** [FarisHijazi/Rarbg-Enhancer-UserScript#9]
Hi, this wonderful extension stopped working for me and when I open console it shows this:

RARBG Enhancer.user.js:99884 TypeError: Cannot set properties of undefined (setting 'GM_fetch2')
    at RARBG Enhancer.user.js:97595:24
    at RARBG Enhancer.user.js:99884:3
    at Proxy.window.VMina7ijcdr6bb9gt581 (RARBG Enhancer.user.js:99884:7)
    at a (injected-web.js:1:20074)
    at v (injected-web.js:1:20181)
    at set (injected-web.js:1:19953)
    at RARBG Enhancer.user.js:1:28

**Comment by FarisHijazi** [comment]
thanks for opening the issue, when does this issue happen?

make sure the script is up to date


also could you click on the link that the error gives you and send a screenshot of the code
because the line numbers change depending on what other extensions you have open, I'll need to see the exact code

please provide me a way of reproducing your error, the script works perfectly fine with me.

**Comment by Michedelic** [comment]
This happens everytime I go into rarbg, I tried disabling all extensions and clearing cookies except ViolentMonkey. Clicking the first link, it shows this:
![image](https://user-images.githubusercontent.com/26649024/158815977-dc0d10f7-d1b6-44ff-b1be-4b45db0fdee2.png)

I uninstalled and reinstalled the Userscript and the extension itself, but it still happens

**Comment by FarisHijazi** [comment]
Please try using Tampermonkey instead of violentMonkey and let me know hoe that works out

Also for the screenshot, could you send the screenshot pointing at the line containing `GM_fetch2...`

**Comment by Michedelic** [comment]
Ok, I disabled ViolentMonkey and installed Tampermonkey and it's working. Maybe it's an issue with the extension? It worked before without issue though.
I have the other screenshot if it helps:
![image](https://user-images.githubusercontent.com/26649024/158818565-d5ac0a21-5fb3-462a-a528-d3ee959ea352.png)

**Comment by FarisHijazi** [comment]
Ok i think i have a solution, I'll fix this in the next update.

That line containing `unsafeWindow.GM_fetch2` is the issue.
Commenting it should solve the issue.

I'll remove it in the next update
Not sure why this still works for Tampermonkey but not violentMonkey

**Comment by FarisHijazi** [comment]
@Michedelic should be resolved, please let me know if the issue persists (make sure to update your script to the latest version first)
